# Generated by Django 4.0.3 on 2022-06-22 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_home_image1_alter_home_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.user'),
        ),
    ]
