# Generated by Django 4.0.3 on 2022-06-26 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_home_image1_remove_home_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='area',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='bathrooms',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='bedrooms',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='garage',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='garden',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='home',
            name='price',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='status',
            field=models.CharField(default='For sale', max_length=20),
        ),
    ]
