# Generated by Django 4.0.3 on 2022-06-17 15:57

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('status', models.CharField(max_length=20)),
                ('area', models.FloatField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('garage', models.IntegerField()),
                ('garden', models.IntegerField()),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('owner', models.CharField(max_length=50)),
                ('image1', models.ImageField(default='default.png', upload_to='upload')),
                ('image2', models.ImageField(default='default.png', upload_to='upload')),
                ('image3', models.ImageField(default='default.png', upload_to='upload')),
                ('image4', models.ImageField(default='default.png', upload_to='upload')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=264)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('image', models.ImageField(default='default.png', upload_to='upload')),
            ],
        ),
    ]
