# Generated by Django 4.0.3 on 2022-06-25 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='image1',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='home',
            name='image2',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='home',
            name='image3',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='home',
            name='image4',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
