# Generated by Django 4.0.3 on 2022-06-25 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_home_image1_alter_home_image2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='home',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='home',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='home',
            name='image4',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='default.png', upload_to='')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.home')),
            ],
        ),
    ]
