# Generated by Django 4.0.3 on 2022-06-26 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_home_area_alter_home_bathrooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='bathrooms',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='home',
            name='bedrooms',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='home',
            name='garage',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='home',
            name='garden',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
