# Generated by Django 4.0.3 on 2022-06-26 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_home_bathrooms_alter_home_bedrooms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='thumbnail',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
